// src/pages/lobby.vue
<template>
  <header>
    <h1>LOBBY (<span>{{ game.lobbyCode }}</span>)</h1>
  </header>
  <main>
    <div>
      <section>
        <h2>Jogadores</h2>
        <ul>
          <li v-for="p in game.players" :key="p.name">
            {{ p.name }}{{ p.ready ? '🟩' : '🟥' }}
          </li>
        </ul>
      </section>
      <div className="vbar"></div>
      <section>
        <h2>Coisas</h2>
        <ul class="things">
          <li v-for="t in game.things" :key="t">{{ t }}</li>
        </ul>
        <div className="inputGroup">
          <input
            type="text"
            placeholder="Qual sua sugestão?"
            v-model="suggestion"
            @keydown="suggestOnEnter"
          />
          <button type="button" @click="suggest">Enviar</button>
        </div>
      </section>
    </div>
    <button id="ready" @click="game.ready">ESTOU PRONTO!</button>
  </main>
</template>

<script lang="ts" setup>
import { ref } from 'vue';
import { useRouter } from 'vue-router';
import { onEnter } from '../composables/enter.ts';
import { useGameStore } from '../stores/game.ts';

const game = useGameStore();
const router = useRouter();

const suggestion = ref('');

const suggest = () => {
  console.log('suggesting', suggestion.value);

  game.suggest(suggestion.value);
  suggestion.value = '';
};
const suggestOnEnter = onEnter(suggest);

game.gameStartLogic(() => {
  // TODO countdown
  router.push({ name: 'game' });
});
</script>

<style src="../assets/lobby.css" scoped></style>

// routes/lobby.tsx
import "@/assets/lobby.css";
import { Button } from "@/components/Button.tsx";
import { Input } from "@/components/Input.tsx";
import { GameContext } from "@/routes/_app.tsx";
import { define } from "@/utils.ts";
import { computed, useSignal } from "@preact/signals";
import { useContext } from "preact/hooks";

export default define.page(function Lobby(ctx) {
  const client = useContext(GameContext);

  const players = computed(() =>
    client
      .players
      .value
      .map((p) => <li key={p}>{p}</li>)
  );

  const things = computed(() =>
    client
      .things
      .value
      .map((t) => <li key={t}>{t}</li>)
  );

  const suggestion = useSignal("");
  const suggest = () => {
    client.suggest(suggestion.value);
    suggestion.value = "";
  };

  return (
    <>
      <header>
        <h1>
          LOBBY
        </h1>
      </header>
      <main>
        <div>
          <section>
            <h2>Jogadores</h2>
            <ul>
              {players}
            </ul>
          </section>
          <div className="vbar"></div>
          <section>
            <h2>Coisas</h2>
            <div className="inputgroup">
              <Input
                type="text"
                placeholder="Qual sua sugestão?"
                value={suggestion.value}
                onInput={(e) => suggestion.value = e.currentTarget.value}
                onEnter={suggest}
              />
              <Button onClick={suggest}>Enviar</Button>
            </div>
            <ul>
              {things}
            </ul>
          </section>
        </div>
        <button type="button">ESTOU PRONTO!</button>
      </main>
    </>
  );
});
