// routes/game.tsx
import "@/assets/game.css";
import { GameContext } from "@/routes/_app.tsx";
import { define } from "@/utils.ts";
import { useSignal } from "@preact/signals";
import { useContext, useRef } from "preact/hooks";
import { Button } from "@/components/Button.tsx";

export default define.page(function Game(ctx) {
  const client = useContext(GameContext);

  const vote = (thing: "L" | "R") => () => {
    const isL = thing === "L";
    client.vote(isL ? thingL : thingR);
    if (isL) {
      disabledL.value = true;
      disabledR.value = false;
    } else {
      disabledL.value = false;
      disabledR.value = true;
    }
  };

  client.roundEndLogic = () => {
    winnerModal.current?.showModal();
  };

  client.roundStartLogic = () => {
    winnerModal.current?.close();
    disabledL.value = false;
    disabledR.value = false;
  };

  const [votesL, votesR] = client.votes;
  const [thingL, thingR] = client.roundThings;
  const disabledL = useSignal(false);
  const disabledR = useSignal(false);

  const winnerModal = useRef<HTMLDialogElement>(null);

  return (
    <>
      <dialog ref={winnerModal} id="winner">
        <h2>Vencedor{client.gameEnd.value ? null : " da rodada"}</h2>
        <span>{client.winner.value}</span>
      </dialog>

      <header>
        <h1>RODADA {client.round}</h1>
      </header>

      <main>
        <section>
          <span>{thingL}</span>
          <Button onClick={vote("L")} disabled={disabledL.value}>VOTAR</Button>
          <ul>
            {votesL.value.map((p) => <li key={p}>{p}</li>)}
          </ul>
        </section>
        <div className="vbar"></div>
        <section>
          <span>{thingR}</span>
          <Button onClick={vote("R")} disabled={disabledR.value}>VOTAR</Button>
          <ul>
            {votesR.value.map((p) => <li key={p}>{p}</li>)}
          </ul>
        </section>
      </main>
    </>
  );
});

// src/client/pages/game.vue
<template>
  <dialog ref="winnerModal" id="winner">
    <span class="left">🎉 </span
    ><span class="fancytext_tiny"
      >Vencedor{{ game.gameEnd ? null : ' da rodada' }}</span
    ><span> 🎉</span>
    <h2 class="fancytext_big">{{ game.winner }}</h2>
  </dialog>

  <header>
    <h1 class="fancytext_big">RODADA {{ game.round }}</h1>
    <h2 class="fancytext_tiny">{{ game.lobbyCode }}</h2>
  </header>

  <main>
    <section>
      <span class="fancytext_mid">{{ votes.thingL }}</span>
      <button @click="voteL" :disabled="disabledL">VOTAR</button>
      <ul>
        <li class="fancytext_tiny" v-for="v in votes.votesL" :key="v">
          {{ v }}
        </li>
      </ul>
    </section>
    <section>
      <span class="fancytext_mid">{{ votes.thingR }}</span>
      <button @click="voteR" :disabled="disabledR">VOTAR</button>
      <ul>
        <li class="fancytext_tiny" v-for="v in votes.votesR" :key="v">
          {{ v }}
        </li>
      </ul>
    </section>
  </main>
</template>

<script lang="ts" setup>
import { useGameStore } from '@/client/stores/game';
import { useVoteStore } from '@/client/stores/votes';
import { ref, useTemplateRef } from 'vue';

const game = useGameStore();
const votes = useVoteStore();

const disabledL = ref(false);
const disabledR = ref(false);

const winnerModal = useTemplateRef('winnerModal');

game.roundEndLogic(() => {
  winnerModal.value?.showModal();
});

game.roundStartLogic(() => {
  winnerModal.value?.close();
  disabledL.value = false;
  disabledR.value = false;
});

const voteL = () => {
  game.vote(votes.thingL);
  disabledL.value = true;
  disabledR.value = false;
};

const voteR = () => {
  game.vote(votes.thingR);
  disabledL.value = false;
  disabledR.value = true;
};
</script>

<style src="../assets/game.css" scoped></style>
