// routes/lobby.tsx
import "@/assets/lobby.css";
import { Button } from "@/components/Button.tsx";
import { Input } from "@/components/Input.tsx";
import { GameContext } from "@/routes/_app.tsx";
import { define } from "@/utils.ts";
import { computed, useSignal } from "@preact/signals";
import { useContext } from "preact/hooks";

export default define.page(function Lobby(ctx) {
  const client = useContext(GameContext);

  const players = computed(() =>
    client
      .players
      .value
      .map((p) => <li key={p}>{p}</li>)
  );

  const things = computed(() =>
    client
      .things
      .value
      .map((t) => <li key={t}>{t}</li>)
  );

  const suggestion = useSignal("");
  const suggest = () => {
    client.suggest(suggestion.value);
    suggestion.value = "";
  };

  return (
    <>
      <header>
        <h1>
          LOBBY
        </h1>
      </header>
      <main>
        <div>
          <section>
            <h2>Jogadores</h2>
            <ul>
              {players}
            </ul>
          </section>
          <div className="vbar"></div>
          <section>
            <h2>Coisas</h2>
            <div className="inputgroup">
              <Input
                type="text"
                placeholder="Qual sua sugestão?"
                value={suggestion.value}
                onInput={(e) => suggestion.value = e.currentTarget.value}
                onEnter={suggest}
              />
              <Button onClick={suggest}>Enviar</Button>
            </div>
            <ul>
              {things}
            </ul>
          </section>
        </div>
        <button type="button">ESTOU PRONTO!</button>
      </main>
    </>
  );
});

// src/client/pages/lobby.vue
<template>
  <header>
    <h1 class="fancytext_big">
      LOBBY - <span>{{ game.lobbyCode }}</span>
    </h1>
  </header>
  <main>
    <section class="players">
      <h2 class="fancytext_small">Jogadores</h2>
      <ul>
        <li v-for="p in game.players" :key="p.name">
          {{ p.ready ? '🟩' : '🟥' }} {{ p.name }}
        </li>
      </ul>
      <button
        @click="handleReady"
        :disabled="disabledInputs || game.things.length < 2"
        class="ready"
      >
        {{isReady ? 'Aguardando jogadores...':  'Começar partida' }}
      </button>
    </section>
    <section class="things">
      <h2 class="fancytext_small">Coisas</h2>
      <ul class="things">
        <li v-for="t in game.things" :key="t">{{ t }}</li>
      </ul>
      <div className="inputGroup">
        <input
          type="text"
          placeholder="Qual sua sugestão?"
          v-model="suggestion"
          :disabled="disabledInputs"
          @keydown="suggestOnEnter"
          required
        />
        <button
          type="button"
          @click="suggest"
          :disabled="disabledInputs || suggestion.length === 0"
        >
          Enviar
        </button>
      </div>
    </section>
  </main>
</template>

<script lang="ts" setup>
import { ref } from 'vue';
import { useRouter } from 'vue-router';
import { onEnter } from '@/client/composables/enter.ts';
import { useGameStore } from '@/client/stores/game.ts';

const game = useGameStore();
const router = useRouter();

const suggestion = ref('');
const disabledInputs = ref(false);
const isReady = ref(false);

const handleReady = () => {
  disabledInputs.value = true;
  isReady.value = true;
  game.ready();
};

const suggest = () => {
  game.suggest(suggestion.value);
  suggestion.value = '';
};

const suggestOnEnter = onEnter(suggest);

game.gameStartLogic(() => {
  // TODO countdown
  router.push({ name: 'game' });
});
</script>

<style src="../assets/lobby.css" scoped></style>
